### ISSUE TITLE
Training hangs

### ISSUE THREAD

**Issue by polajnta** [fstrub95/Autoencoders_cf#11]
Hi,

I am trying to train your network. When I run the command

> th main.lua  -file ../data/ml-10M100K/movieLens-10M.t7 -conf ../conf/conf.movieLens.10M.V.lua  -save network.t7 -type V -meta 1 -gpu 0

it proceeds well until I hit this stage:

> 
> nn.Sequential {
>   [input -> (1) -> (2) -> (3) -> (4) -> (5) -> (6) -> output]
>   (1): cfn.AppenderSparseOut
>   (2): nnsparse.SparseLinearBatch(69897 -> 770)
>   (3): nn.Tanh
>   (4): cfn.AppenderOut
>   (5): nn.Linear(789 -> 69878)
>   (6): nn.Tanh
> }
>  [>....................................... 1/50 ........................................]  ETA: 0ms | Step: 0ms   
> 

then hangs....
on two different machines, with/without gpu.

**Comment by polajnta** [comment]
Sorry, fixed it now. It keeps using some default GPU and does not choose the one with the specified index. It would need a line from cutorch to do that. It's training on CPU fine.

**Comment by fstrub95** [comment]
Np, tell me if you need more info
