### ISSUE TITLE
ClassicLoader Issues

### ISSUE THREAD

**Issue by polajnta** [fstrub95/Autoencoders_cf#12]
Hi,

There are several small bugs in the ClassicLoader file

line 64 needs a return statement:
`return denseTensor:indexCopy(1, index:long(), data)`

there are two function headers for
`function classicLoader:LoadMetaU(conf)`

one should be 
`function classicLoader:LoadMetaV(conf)`

in getRegex
`(%d:%-?%d%.?%d*)` needs to change `(%d+:%-?%d%.?%d*)` to cover indices > 9
in

`function classicLoader:LoadMeta(fileName, type, GetXindex)`

type is a function in lua and needs to change to something like typeVar throughout the function
`function classicLoader:LoadMeta(fileName, typeVar, GetXindex) `
 
`maxId = math.max(maxId, idInfo)`
needs to change
`maxId = math.max(maxId + offset, idInfo + offset)`

need to add type checking when computing dense side information (around line 118) otherwise it errors out when it gets to the metadata entries at the end. 
 ```
     if type(oneInfo) == "table" then
        if oneInfo.fullSparse then
	    oneInfo.full = densify(oneInfo.fullSparse,maxId)
	 else
	    oneInfo.full       = torch.zeros(maxId)
	    oneInfo.fullSparse = torch.Tensor()
	 end
      end 
```

**Comment by fstrub95** [comment]
Thank you a lot for your feedback! I have to run the code again to test it before pushing it.
My apologize as I have not use classic loader except on very naive use case, yet I  feel bad to providd something buggy 😕
Do you want to do a pull request? Otherwise I will push the code next week (I am rushing for a deadline so I cannot exactly tell you when it will be done )
Thx again!

**Comment by polajnta** [comment]
Oh I wouldn’t feel comfortable, you should make sure it’s right. Maybe I can encdode my data into a format of one of the other datasets and use one of the the other loaders.

**Comment by fstrub95** [comment]
I received the code, I will test it and push it as soon as possible!

**Comment by polajnta** [comment]
yeah no worries.

**Comment by fstrub95** [comment]
Done!
https://github.com/fstrub95/Autoencoders_cf/commit/685baa88401372dd27ea0784976f9324579d6a40
