### ISSUE TITLE
Does anyone know where can find the Tensorflow implementation?

### ISSUE THREAD

**Issue by yushuai** [fstrub95/Autoencoders_cf#15]
I am not good at torch...

**Comment by fstrub95** [comment]
Unfortunately, I am not aware of a tensorflow implementation :(
Yet, you may want to have a look to this paper/implementation : 
 - https://arxiv.org/abs/1708.01715
 - https://github.com/NVIDIA/DeepRecommender/tree/master/reco_encoder/model
It is not exactly this paper, it is not exactly in tensorflow... but well... it is interesting :)

**Comment by yushuai** [comment]
Thanks for the paper and the codes!  Though I am not good at torch,  I am very familiar with PyTorch.
