### ISSUE TITLE
Data in .t7 format

### ISSUE THREAD

**Issue by gheinrich** [fstrub95/Autoencoders_cf#2]
Hi and thanks for making this project online! I am trying to use branch `AutoEnc_1.1.0.0` to test the GPU implementation however I am not sure how to convert the MovieLens dataset from `.dat` to `.t7` format. I tried using the Jester dataset but got an error...

```
$ th main.lua -file ../data/jester/jester-full.t7 
Options:    
 - gpu       : true 
 - file      : ../data/jester/jester-full.t7    
 - seed      : 1234 
 - conf      : config.template.lua  
loading data... 
/home/greg/ws/torch/install/bin/luajit: /home/greg/ws/torch/install/share/lua/5.1/torch/File.lua:322: unknown object
stack traceback:
    [C]: in function 'error'
    /home/greg/ws/torch/install/share/lua/5.1/torch/File.lua:322: in function 'readObject'
    /home/greg/ws/torch/install/share/lua/5.1/torch/File.lua:347: in function 'load'
    main.lua:56: in main chunk
    [C]: in function 'dofile'
    ...g/ws/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:145: in main chunk
    [C]: at 0x00406670
```

Sorry if I missed the relevant bit in the documentation.

**Comment by fstrub95** [comment]
Hi, 
You first need to turn the data into torch format with AutoEnc_1.0.0.0 with the data.lua file.

$> th data.lua -ratings ../data/movieLens/ratings-1M.dat -out ./movieLens-1M.t7
$> th main.lua -file ./movieLens-1M.t7 -gpu true 

If you have your own data format, you need to create a new object that inherit from DataLoader.

A good example with a GPU is movieLens-10M : http://grouplens.org/datasets/movielens/10m/

The following configuration provide a RMSE around 0.780 in 6~8 minutes on a GTX 980. 

configV =
{
   useMetaData = false, --still under development
   layer1 =
   {
      layerSize = 700,
      {
         criterion = nnsparse.SDAECriterionGPU(nn.MSECriterion(),
         {
            alpha = 1.10,
            beta  = 0.828,
            hideRatio = 0.224,
         }),
         noEpoch = 15,
         miniBatchSize = 35,
         learningRate = 0.04,
         learningRateDecay = 0.225,
         weightDecay = 0.08,
      },

   }
}

Yet, this branch is still under development. We plan to send a paper for either ICML 2016 or KDD 2016. Thus, the code is not very clean and there are still some nasty hacks for fast prototyping.  
If you come back in 3/4 weeks. A final version of the code/paper will be pushed.

**Comment by gheinrich** [comment]
Thanks!

**Comment by fstrub95** [comment]
I updated the main branch. You should now be able to easily run the experiments.
I'll put my new paper on arxiv very soon, in the meantime, you can download it from my website: http://florian-strub.com/AutoEnc.pdf
If you face some issues, I'll fix them asap!
Kind regards, 
STRUB Florian

**Comment by gheinrich** [comment]
Thanks Florian!

**Comment by jamie083146** [comment]
hi,
   I'm really new in linux, and I try to convert my dataset from .txt to .t7,but.....failed.
   I confused about how to create a new object that inherit from DataLoader.
   Hope you could write for me more attentively.

**Comment by fstrub95** [comment]
Hi Jamie, 
If you do not know Lua, you can use the classic loader (cf doc) that takes as input a very simple csv file.
Therefore, you can easily convert any kind of input files into this csv format with your favorite language. (python, matlab) etc.
kind regards
Florian
