### ISSUE TITLE
Error when run main.lua

### ISSUE THREAD

**Issue by valdersoul** [fstrub95/Autoencoders_cf#6]
When use the latest torch, found this error:

/torch/install/bin/luajit: tools/SDAECriterionGPU.lua:65: invalid arguments: CudaTensor CudaTensor CudaTensor
expected arguments: [_CudaTensor_] CudaTensor CudaByteTensor
stack traceback:
        [C]: in function 'maskedSelect'
        tools/SDAECriterionGPU.lua:65: in function 'prepareInput'
        misc/AutoEncoderTrainer.lua:97: in function 'opfunc'
        /home/valder/torch/install/share/lua/5.1/optim/sgd.lua:44: in function 'sgd'
        misc/AutoEncoderTrainer.lua:121: in function 'Train'
        misc/AutoEncoderTrainer.lua:266: in function 'Execute'
        misc/TrainNetwork.lua:150: in function 'TrainNetwork'
        main.lua:69: in main chunk
        [C]: in function 'dofile'
        ...lder/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:145: in main chunk
        [C]: at 0x00406670

Is this something to do with the torch version?

**Comment by valdersoul** [comment]
Solved

**Comment by fstrub95** [comment]
Hi,
I have to update the code to fit the new torch api. I am currently on
holidays, so, I will fix it in two weeks.
Thx for reporting!
Florian

**Comment by fstrub95** [comment]
Fixed!
