### ISSUE TITLE
cuda runtime error (2) : out of memory

### ISSUE THREAD

**Issue by leetiantian** [fstrub95/Autoencoders_cf#9]
When I ran the movieLens-10M dataset， I found this error:
tian@ubuntu:~/RecSys/Autoencoders_cf-master/src$ th main.lua  -file ../data/ml-10M100K/movieLens-10M.t7 -conf ../conf/conf.movieLens.10M.V.lua  -save network.t7 -type V -meta 1 -gpu 1
Options:    
- meta      : 1  
- seed      : 0  
- type      : V  
- conf      : ../conf/conf.movieLens.10M.V.lua 
- gpu       : 1  
- file      : ../data/ml-10M100K/movieLens-10M.t7  
- save      : network.t7  
  Load training configuration...  
  Load data...  
  Loading data from disk...  

Users loaded      : 69878  
Items loaded      : 10677   

No Train ratings  : 8999969 
No Test  ratings  : 1000085 
Training ratio    : 0.89999204004298  
Training density  : 0.012062888245563   

Loading cunn... 
Loading data to GPU...  
Unbias the data...  
Data was successfully preloaded...  
Training network  
THCudaCheck FAIL file=/tmp/luarocks_cutorch-scm-1-2104/cutorch/lib/THC/generic/THCStorage.cu line=40 error=2 : out of memory
/home/tian/torch/install/bin/lua: /home/tian/torch/install/share/lua/5.2/nn/utils.lua:11: cuda runtime error (2) : out of memory at /tmp/luarocks_cutorch-scm-1-2104/cutorch/lib/THC/generic/THCStorage.cu:40
stack traceback:
    [C]: in function 'resize'
    /home/tian/torch/install/share/lua/5.2/nn/utils.lua:11: in function 'torch_Storage_type'
    /home/tian/torch/install/share/lua/5.2/nn/utils.lua:57: in function 'recursiveType'
    /home/tian/torch/install/share/lua/5.2/nn/Module.lua:152: in function 'type'
    /home/tian/torch/install/share/lua/5.2/nn/utils.lua:45: in function 'recursiveType'
    /home/tian/torch/install/share/lua/5.2/nn/utils.lua:41: in function 'recursiveType'
    /home/tian/torch/install/share/lua/5.2/nn/Module.lua:152: in function </home/tian/torch/install/share/lua/5.2/nn/Module.lua:143>
    (...tail calls...)
    misc/TrainNetwork.lua:114: in function 'TrainNetwork'
    main.lua:69: in main chunk
    [C]: in function 'dofile'
    ...tian/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:145: in main chunk
    [C]: in ?

I thought maybe it is because of LuaJit memory limit so I used Lua5.2 instead.But the error still occured.  I also tried to change the batch size to 1 but it still doesn't work.

**Comment by fstrub95** [comment]
What is your GPU? movieLens-10M requires a bit more than 2Go of GPU-RAM.

**Comment by leetiantian** [comment]
My GPU is only 1 GB. I will try the movieLens-10M with a different machine.
